<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SG_01.Web.Blazor</AssemblyName>
    <RootNamespace>SG_01.Web.Blazor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sg01.web.2026.ServiceDefaults\sg01.web.2026.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\CommonLocalization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommonLocalization.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\CommonLocalization.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>CommonLocalization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
